// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderPayment.proto

package dk.pejomi.orderPaymentGRPC;

public final class OrderPayment {
  private OrderPayment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderItemDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.pejomi.orderPaymentGRPC.OrderItemDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 menuItemId = 2;</code>
     * @return The menuItemId.
     */
    long getMenuItemId();

    /**
     * <code>double price = 5;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code dk.pejomi.orderPaymentGRPC.OrderItemDto}
   */
  public  static final class OrderItemDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.pejomi.orderPaymentGRPC.OrderItemDto)
      OrderItemDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderItemDto.newBuilder() to construct.
    private OrderItemDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderItemDto() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderItemDto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderItemDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              menuItemId_ = input.readInt64();
              break;
            }
            case 41: {

              price_ = input.readDouble();
              break;
            }
            case 48: {

              quantity_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.class, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int MENUITEMID_FIELD_NUMBER = 2;
    private long menuItemId_;
    /**
     * <code>int64 menuItemId = 2;</code>
     * @return The menuItemId.
     */
    public long getMenuItemId() {
      return menuItemId_;
    }

    public static final int PRICE_FIELD_NUMBER = 5;
    private double price_;
    /**
     * <code>double price = 5;</code>
     * @return The price.
     */
    public double getPrice() {
      return price_;
    }

    public static final int QUANTITY_FIELD_NUMBER = 6;
    private int quantity_;
    /**
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    public int getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (menuItemId_ != 0L) {
        output.writeInt64(2, menuItemId_);
      }
      if (price_ != 0D) {
        output.writeDouble(5, price_);
      }
      if (quantity_ != 0) {
        output.writeInt32(6, quantity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (menuItemId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, menuItemId_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, price_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, quantity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto)) {
        return super.equals(obj);
      }
      dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto other = (dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto) obj;

      if (getId()
          != other.getId()) return false;
      if (getMenuItemId()
          != other.getMenuItemId()) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + MENUITEMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMenuItemId());
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.pejomi.orderPaymentGRPC.OrderItemDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.pejomi.orderPaymentGRPC.OrderItemDto)
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.class, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder.class);
      }

      // Construct using dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        menuItemId_ = 0L;

        price_ = 0D;

        quantity_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_descriptor;
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto getDefaultInstanceForType() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.getDefaultInstance();
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto build() {
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto buildPartial() {
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto result = new dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto(this);
        result.id_ = id_;
        result.menuItemId_ = menuItemId_;
        result.price_ = price_;
        result.quantity_ = quantity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto) {
          return mergeFrom((dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto other) {
        if (other == dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getMenuItemId() != 0L) {
          setMenuItemId(other.getMenuItemId());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long menuItemId_ ;
      /**
       * <code>int64 menuItemId = 2;</code>
       * @return The menuItemId.
       */
      public long getMenuItemId() {
        return menuItemId_;
      }
      /**
       * <code>int64 menuItemId = 2;</code>
       * @param value The menuItemId to set.
       * @return This builder for chaining.
       */
      public Builder setMenuItemId(long value) {
        
        menuItemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 menuItemId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMenuItemId() {
        
        menuItemId_ = 0L;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 5;</code>
       * @return The price.
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 5;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 6;</code>
       * @return The quantity.
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 6;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.pejomi.orderPaymentGRPC.OrderItemDto)
    }

    // @@protoc_insertion_point(class_scope:dk.pejomi.orderPaymentGRPC.OrderItemDto)
    private static final dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto();
    }

    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderItemDto>
        PARSER = new com.google.protobuf.AbstractParser<OrderItemDto>() {
      @java.lang.Override
      public OrderItemDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderItemDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderItemDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderItemDto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.pejomi.orderPaymentGRPC.OrderDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 consumerId = 2;</code>
     * @return The consumerId.
     */
    long getConsumerId();

    /**
     * <code>int64 restaurantId = 3;</code>
     * @return The restaurantId.
     */
    long getRestaurantId();

    /**
     * <code>string orderState = 4;</code>
     * @return The orderState.
     */
    java.lang.String getOrderState();
    /**
     * <code>string orderState = 4;</code>
     * @return The bytes for orderState.
     */
    com.google.protobuf.ByteString
        getOrderStateBytes();

    /**
     * <code>double price = 5;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    java.util.List<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto> 
        getOrderItemsDtoList();
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto getOrderItemsDto(int index);
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    int getOrderItemsDtoCount();
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    java.util.List<? extends dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder> 
        getOrderItemsDtoOrBuilderList();
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder getOrderItemsDtoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code dk.pejomi.orderPaymentGRPC.OrderDto}
   */
  public  static final class OrderDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.pejomi.orderPaymentGRPC.OrderDto)
      OrderDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderDto.newBuilder() to construct.
    private OrderDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderDto() {
      orderState_ = "";
      orderItemsDto_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderDto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              consumerId_ = input.readInt64();
              break;
            }
            case 24: {

              restaurantId_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              orderState_ = s;
              break;
            }
            case 41: {

              price_ = input.readDouble();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                orderItemsDto_ = new java.util.ArrayList<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto>();
                mutable_bitField0_ |= 0x00000001;
              }
              orderItemsDto_.add(
                  input.readMessage(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          orderItemsDto_ = java.util.Collections.unmodifiableList(orderItemsDto_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.class, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int CONSUMERID_FIELD_NUMBER = 2;
    private long consumerId_;
    /**
     * <code>int64 consumerId = 2;</code>
     * @return The consumerId.
     */
    public long getConsumerId() {
      return consumerId_;
    }

    public static final int RESTAURANTID_FIELD_NUMBER = 3;
    private long restaurantId_;
    /**
     * <code>int64 restaurantId = 3;</code>
     * @return The restaurantId.
     */
    public long getRestaurantId() {
      return restaurantId_;
    }

    public static final int ORDERSTATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object orderState_;
    /**
     * <code>string orderState = 4;</code>
     * @return The orderState.
     */
    public java.lang.String getOrderState() {
      java.lang.Object ref = orderState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderState_ = s;
        return s;
      }
    }
    /**
     * <code>string orderState = 4;</code>
     * @return The bytes for orderState.
     */
    public com.google.protobuf.ByteString
        getOrderStateBytes() {
      java.lang.Object ref = orderState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 5;
    private double price_;
    /**
     * <code>double price = 5;</code>
     * @return The price.
     */
    public double getPrice() {
      return price_;
    }

    public static final int ORDERITEMSDTO_FIELD_NUMBER = 6;
    private java.util.List<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto> orderItemsDto_;
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    public java.util.List<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto> getOrderItemsDtoList() {
      return orderItemsDto_;
    }
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    public java.util.List<? extends dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder> 
        getOrderItemsDtoOrBuilderList() {
      return orderItemsDto_;
    }
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    public int getOrderItemsDtoCount() {
      return orderItemsDto_.size();
    }
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto getOrderItemsDto(int index) {
      return orderItemsDto_.get(index);
    }
    /**
     * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
     */
    public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder getOrderItemsDtoOrBuilder(
        int index) {
      return orderItemsDto_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (consumerId_ != 0L) {
        output.writeInt64(2, consumerId_);
      }
      if (restaurantId_ != 0L) {
        output.writeInt64(3, restaurantId_);
      }
      if (!getOrderStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, orderState_);
      }
      if (price_ != 0D) {
        output.writeDouble(5, price_);
      }
      for (int i = 0; i < orderItemsDto_.size(); i++) {
        output.writeMessage(6, orderItemsDto_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (consumerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, consumerId_);
      }
      if (restaurantId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, restaurantId_);
      }
      if (!getOrderStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, orderState_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, price_);
      }
      for (int i = 0; i < orderItemsDto_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, orderItemsDto_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto)) {
        return super.equals(obj);
      }
      dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto other = (dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto) obj;

      if (getId()
          != other.getId()) return false;
      if (getConsumerId()
          != other.getConsumerId()) return false;
      if (getRestaurantId()
          != other.getRestaurantId()) return false;
      if (!getOrderState()
          .equals(other.getOrderState())) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (!getOrderItemsDtoList()
          .equals(other.getOrderItemsDtoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CONSUMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getConsumerId());
      hash = (37 * hash) + RESTAURANTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRestaurantId());
      hash = (37 * hash) + ORDERSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderState().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      if (getOrderItemsDtoCount() > 0) {
        hash = (37 * hash) + ORDERITEMSDTO_FIELD_NUMBER;
        hash = (53 * hash) + getOrderItemsDtoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.pejomi.orderPaymentGRPC.OrderDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.pejomi.orderPaymentGRPC.OrderDto)
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.class, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder.class);
      }

      // Construct using dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrderItemsDtoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        consumerId_ = 0L;

        restaurantId_ = 0L;

        orderState_ = "";

        price_ = 0D;

        if (orderItemsDtoBuilder_ == null) {
          orderItemsDto_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          orderItemsDtoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_descriptor;
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto getDefaultInstanceForType() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.getDefaultInstance();
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto build() {
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto buildPartial() {
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto result = new dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.consumerId_ = consumerId_;
        result.restaurantId_ = restaurantId_;
        result.orderState_ = orderState_;
        result.price_ = price_;
        if (orderItemsDtoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            orderItemsDto_ = java.util.Collections.unmodifiableList(orderItemsDto_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orderItemsDto_ = orderItemsDto_;
        } else {
          result.orderItemsDto_ = orderItemsDtoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto) {
          return mergeFrom((dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto other) {
        if (other == dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getConsumerId() != 0L) {
          setConsumerId(other.getConsumerId());
        }
        if (other.getRestaurantId() != 0L) {
          setRestaurantId(other.getRestaurantId());
        }
        if (!other.getOrderState().isEmpty()) {
          orderState_ = other.orderState_;
          onChanged();
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (orderItemsDtoBuilder_ == null) {
          if (!other.orderItemsDto_.isEmpty()) {
            if (orderItemsDto_.isEmpty()) {
              orderItemsDto_ = other.orderItemsDto_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrderItemsDtoIsMutable();
              orderItemsDto_.addAll(other.orderItemsDto_);
            }
            onChanged();
          }
        } else {
          if (!other.orderItemsDto_.isEmpty()) {
            if (orderItemsDtoBuilder_.isEmpty()) {
              orderItemsDtoBuilder_.dispose();
              orderItemsDtoBuilder_ = null;
              orderItemsDto_ = other.orderItemsDto_;
              bitField0_ = (bitField0_ & ~0x00000001);
              orderItemsDtoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrderItemsDtoFieldBuilder() : null;
            } else {
              orderItemsDtoBuilder_.addAllMessages(other.orderItemsDto_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long consumerId_ ;
      /**
       * <code>int64 consumerId = 2;</code>
       * @return The consumerId.
       */
      public long getConsumerId() {
        return consumerId_;
      }
      /**
       * <code>int64 consumerId = 2;</code>
       * @param value The consumerId to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerId(long value) {
        
        consumerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 consumerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumerId() {
        
        consumerId_ = 0L;
        onChanged();
        return this;
      }

      private long restaurantId_ ;
      /**
       * <code>int64 restaurantId = 3;</code>
       * @return The restaurantId.
       */
      public long getRestaurantId() {
        return restaurantId_;
      }
      /**
       * <code>int64 restaurantId = 3;</code>
       * @param value The restaurantId to set.
       * @return This builder for chaining.
       */
      public Builder setRestaurantId(long value) {
        
        restaurantId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 restaurantId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRestaurantId() {
        
        restaurantId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object orderState_ = "";
      /**
       * <code>string orderState = 4;</code>
       * @return The orderState.
       */
      public java.lang.String getOrderState() {
        java.lang.Object ref = orderState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderState_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderState = 4;</code>
       * @return The bytes for orderState.
       */
      public com.google.protobuf.ByteString
          getOrderStateBytes() {
        java.lang.Object ref = orderState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderState = 4;</code>
       * @param value The orderState to set.
       * @return This builder for chaining.
       */
      public Builder setOrderState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderState = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderState() {
        
        orderState_ = getDefaultInstance().getOrderState();
        onChanged();
        return this;
      }
      /**
       * <code>string orderState = 4;</code>
       * @param value The bytes for orderState to set.
       * @return This builder for chaining.
       */
      public Builder setOrderStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderState_ = value;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 5;</code>
       * @return The price.
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 5;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private java.util.List<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto> orderItemsDto_ =
        java.util.Collections.emptyList();
      private void ensureOrderItemsDtoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          orderItemsDto_ = new java.util.ArrayList<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto>(orderItemsDto_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder> orderItemsDtoBuilder_;

      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public java.util.List<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto> getOrderItemsDtoList() {
        if (orderItemsDtoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderItemsDto_);
        } else {
          return orderItemsDtoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public int getOrderItemsDtoCount() {
        if (orderItemsDtoBuilder_ == null) {
          return orderItemsDto_.size();
        } else {
          return orderItemsDtoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto getOrderItemsDto(int index) {
        if (orderItemsDtoBuilder_ == null) {
          return orderItemsDto_.get(index);
        } else {
          return orderItemsDtoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder setOrderItemsDto(
          int index, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto value) {
        if (orderItemsDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderItemsDtoIsMutable();
          orderItemsDto_.set(index, value);
          onChanged();
        } else {
          orderItemsDtoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder setOrderItemsDto(
          int index, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder builderForValue) {
        if (orderItemsDtoBuilder_ == null) {
          ensureOrderItemsDtoIsMutable();
          orderItemsDto_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderItemsDtoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder addOrderItemsDto(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto value) {
        if (orderItemsDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderItemsDtoIsMutable();
          orderItemsDto_.add(value);
          onChanged();
        } else {
          orderItemsDtoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder addOrderItemsDto(
          int index, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto value) {
        if (orderItemsDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderItemsDtoIsMutable();
          orderItemsDto_.add(index, value);
          onChanged();
        } else {
          orderItemsDtoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder addOrderItemsDto(
          dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder builderForValue) {
        if (orderItemsDtoBuilder_ == null) {
          ensureOrderItemsDtoIsMutable();
          orderItemsDto_.add(builderForValue.build());
          onChanged();
        } else {
          orderItemsDtoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder addOrderItemsDto(
          int index, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder builderForValue) {
        if (orderItemsDtoBuilder_ == null) {
          ensureOrderItemsDtoIsMutable();
          orderItemsDto_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderItemsDtoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder addAllOrderItemsDto(
          java.lang.Iterable<? extends dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto> values) {
        if (orderItemsDtoBuilder_ == null) {
          ensureOrderItemsDtoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orderItemsDto_);
          onChanged();
        } else {
          orderItemsDtoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder clearOrderItemsDto() {
        if (orderItemsDtoBuilder_ == null) {
          orderItemsDto_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          orderItemsDtoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public Builder removeOrderItemsDto(int index) {
        if (orderItemsDtoBuilder_ == null) {
          ensureOrderItemsDtoIsMutable();
          orderItemsDto_.remove(index);
          onChanged();
        } else {
          orderItemsDtoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder getOrderItemsDtoBuilder(
          int index) {
        return getOrderItemsDtoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder getOrderItemsDtoOrBuilder(
          int index) {
        if (orderItemsDtoBuilder_ == null) {
          return orderItemsDto_.get(index);  } else {
          return orderItemsDtoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public java.util.List<? extends dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder> 
           getOrderItemsDtoOrBuilderList() {
        if (orderItemsDtoBuilder_ != null) {
          return orderItemsDtoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderItemsDto_);
        }
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder addOrderItemsDtoBuilder() {
        return getOrderItemsDtoFieldBuilder().addBuilder(
            dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.getDefaultInstance());
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder addOrderItemsDtoBuilder(
          int index) {
        return getOrderItemsDtoFieldBuilder().addBuilder(
            index, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.getDefaultInstance());
      }
      /**
       * <code>repeated .dk.pejomi.orderPaymentGRPC.OrderItemDto orderItemsDto = 6;</code>
       */
      public java.util.List<dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder> 
           getOrderItemsDtoBuilderList() {
        return getOrderItemsDtoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder> 
          getOrderItemsDtoFieldBuilder() {
        if (orderItemsDtoBuilder_ == null) {
          orderItemsDtoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDto.Builder, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderItemDtoOrBuilder>(
                  orderItemsDto_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          orderItemsDto_ = null;
        }
        return orderItemsDtoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.pejomi.orderPaymentGRPC.OrderDto)
    }

    // @@protoc_insertion_point(class_scope:dk.pejomi.orderPaymentGRPC.OrderDto)
    private static final dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto();
    }

    public static dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderDto>
        PARSER = new com.google.protobuf.AbstractParser<OrderDto>() {
      @java.lang.Override
      public OrderDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderDto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PaymentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.pejomi.orderPaymentGRPC.PaymentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
     * @return Whether the orderDto field is set.
     */
    boolean hasOrderDto();
    /**
     * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
     * @return The orderDto.
     */
    dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto getOrderDto();
    /**
     * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
     */
    dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDtoOrBuilder getOrderDtoOrBuilder();
  }
  /**
   * Protobuf type {@code dk.pejomi.orderPaymentGRPC.PaymentResponse}
   */
  public  static final class PaymentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.pejomi.orderPaymentGRPC.PaymentResponse)
      PaymentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PaymentResponse.newBuilder() to construct.
    private PaymentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PaymentResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PaymentResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PaymentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder subBuilder = null;
              if (orderDto_ != null) {
                subBuilder = orderDto_.toBuilder();
              }
              orderDto_ = input.readMessage(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(orderDto_);
                orderDto_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse.class, dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERDTO_FIELD_NUMBER = 3;
    private dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto orderDto_;
    /**
     * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
     * @return Whether the orderDto field is set.
     */
    public boolean hasOrderDto() {
      return orderDto_ != null;
    }
    /**
     * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
     * @return The orderDto.
     */
    public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto getOrderDto() {
      return orderDto_ == null ? dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.getDefaultInstance() : orderDto_;
    }
    /**
     * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
     */
    public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDtoOrBuilder getOrderDtoOrBuilder() {
      return getOrderDto();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (orderDto_ != null) {
        output.writeMessage(3, getOrderDto());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (orderDto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOrderDto());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse)) {
        return super.equals(obj);
      }
      dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse other = (dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (hasOrderDto() != other.hasOrderDto()) return false;
      if (hasOrderDto()) {
        if (!getOrderDto()
            .equals(other.getOrderDto())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (hasOrderDto()) {
        hash = (37 * hash) + ORDERDTO_FIELD_NUMBER;
        hash = (53 * hash) + getOrderDto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.pejomi.orderPaymentGRPC.PaymentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.pejomi.orderPaymentGRPC.PaymentResponse)
        dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse.class, dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse.Builder.class);
      }

      // Construct using dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        message_ = "";

        if (orderDtoBuilder_ == null) {
          orderDto_ = null;
        } else {
          orderDto_ = null;
          orderDtoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_descriptor;
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse getDefaultInstanceForType() {
        return dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse build() {
        dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse buildPartial() {
        dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse result = new dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse(this);
        result.success_ = success_;
        result.message_ = message_;
        if (orderDtoBuilder_ == null) {
          result.orderDto_ = orderDto_;
        } else {
          result.orderDto_ = orderDtoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse) {
          return mergeFrom((dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse other) {
        if (other == dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.hasOrderDto()) {
          mergeOrderDto(other.getOrderDto());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto orderDto_;
      private com.google.protobuf.SingleFieldBuilderV3<
          dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDtoOrBuilder> orderDtoBuilder_;
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       * @return Whether the orderDto field is set.
       */
      public boolean hasOrderDto() {
        return orderDtoBuilder_ != null || orderDto_ != null;
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       * @return The orderDto.
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto getOrderDto() {
        if (orderDtoBuilder_ == null) {
          return orderDto_ == null ? dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.getDefaultInstance() : orderDto_;
        } else {
          return orderDtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       */
      public Builder setOrderDto(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto value) {
        if (orderDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderDto_ = value;
          onChanged();
        } else {
          orderDtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       */
      public Builder setOrderDto(
          dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder builderForValue) {
        if (orderDtoBuilder_ == null) {
          orderDto_ = builderForValue.build();
          onChanged();
        } else {
          orderDtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       */
      public Builder mergeOrderDto(dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto value) {
        if (orderDtoBuilder_ == null) {
          if (orderDto_ != null) {
            orderDto_ =
              dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.newBuilder(orderDto_).mergeFrom(value).buildPartial();
          } else {
            orderDto_ = value;
          }
          onChanged();
        } else {
          orderDtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       */
      public Builder clearOrderDto() {
        if (orderDtoBuilder_ == null) {
          orderDto_ = null;
          onChanged();
        } else {
          orderDto_ = null;
          orderDtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder getOrderDtoBuilder() {
        
        onChanged();
        return getOrderDtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       */
      public dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDtoOrBuilder getOrderDtoOrBuilder() {
        if (orderDtoBuilder_ != null) {
          return orderDtoBuilder_.getMessageOrBuilder();
        } else {
          return orderDto_ == null ?
              dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.getDefaultInstance() : orderDto_;
        }
      }
      /**
       * <code>.dk.pejomi.orderPaymentGRPC.OrderDto orderDto = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDtoOrBuilder> 
          getOrderDtoFieldBuilder() {
        if (orderDtoBuilder_ == null) {
          orderDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDto.Builder, dk.pejomi.orderPaymentGRPC.OrderPayment.OrderDtoOrBuilder>(
                  getOrderDto(),
                  getParentForChildren(),
                  isClean());
          orderDto_ = null;
        }
        return orderDtoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.pejomi.orderPaymentGRPC.PaymentResponse)
    }

    // @@protoc_insertion_point(class_scope:dk.pejomi.orderPaymentGRPC.PaymentResponse)
    private static final dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse();
    }

    public static dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaymentResponse>
        PARSER = new com.google.protobuf.AbstractParser<PaymentResponse>() {
      @java.lang.Override
      public PaymentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PaymentResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PaymentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.pejomi.orderPaymentGRPC.OrderPayment.PaymentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022orderPayment.proto\022\032dk.pejomi.orderPay" +
      "mentGRPC\"O\n\014OrderItemDto\022\n\n\002id\030\001 \001(\003\022\022\n\n" +
      "menuItemId\030\002 \001(\003\022\r\n\005price\030\005 \001(\001\022\020\n\010quant" +
      "ity\030\006 \001(\005\"\244\001\n\010OrderDto\022\n\n\002id\030\001 \001(\003\022\022\n\nco" +
      "nsumerId\030\002 \001(\003\022\024\n\014restaurantId\030\003 \001(\003\022\022\n\n" +
      "orderState\030\004 \001(\t\022\r\n\005price\030\005 \001(\001\022?\n\rorder" +
      "ItemsDto\030\006 \003(\0132(.dk.pejomi.orderPaymentG" +
      "RPC.OrderItemDto\"k\n\017PaymentResponse\022\017\n\007s" +
      "uccess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\0226\n\010orderDt" +
      "o\030\003 \001(\0132$.dk.pejomi.orderPaymentGRPC.Ord" +
      "erDto2z\n\023OrderPaymentService\022c\n\016ProcessP" +
      "ayment\022$.dk.pejomi.orderPaymentGRPC.Orde" +
      "rDto\032+.dk.pejomi.orderPaymentGRPC.Paymen" +
      "tResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_pejomi_orderPaymentGRPC_OrderItemDto_descriptor,
        new java.lang.String[] { "Id", "MenuItemId", "Price", "Quantity", });
    internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_pejomi_orderPaymentGRPC_OrderDto_descriptor,
        new java.lang.String[] { "Id", "ConsumerId", "RestaurantId", "OrderState", "Price", "OrderItemsDto", });
    internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_pejomi_orderPaymentGRPC_PaymentResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "OrderDto", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
