apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
        - name: auth
          image: jonasrex/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: auth-service
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080