version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_service
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_password
    ports:
      - "3308:3308"

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
     # SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_service
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/auth-service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root