//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.25 at 04:41:16 PM CET 
//


package dk.pejomi.chartservice.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineChart" type="{http://pejomi.dk/chartservice/xml}lineChart"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineChart"
})
@XmlRootElement(name = "getLineChartRequest")
public class GetLineChartRequest {

    @XmlElement(required = true)
    protected LineChart lineChart;

    /**
     * Gets the value of the lineChart property.
     * 
     * @return
     *     possible object is
     *     {@link LineChart }
     *     
     */
    public LineChart getLineChart() {
        return lineChart;
    }

    /**
     * Sets the value of the lineChart property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineChart }
     *     
     */
    public void setLineChart(LineChart value) {
        this.lineChart = value;
    }

}
