//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.25 at 04:41:16 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://pejomi.dk/chartservice/xml", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.pejomi.chartservice.xml;
