//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.02 at 12:41:15 AM CET 
//


package dk.pejomi.chartsoap.xml;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.pejomi.chartsoap.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.pejomi.chartsoap.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLineChartRequest }
     * 
     */
    public GetLineChartRequest createGetLineChartRequest() {
        return new GetLineChartRequest();
    }

    /**
     * Create an instance of {@link LineChart }
     * 
     */
    public LineChart createLineChart() {
        return new LineChart();
    }

    /**
     * Create an instance of {@link GetLineChartResponse }
     * 
     */
    public GetLineChartResponse createGetLineChartResponse() {
        return new GetLineChartResponse();
    }

    /**
     * Create an instance of {@link GetDoughnutChartRequest }
     * 
     */
    public GetDoughnutChartRequest createGetDoughnutChartRequest() {
        return new GetDoughnutChartRequest();
    }

    /**
     * Create an instance of {@link DoughnutChart }
     * 
     */
    public DoughnutChart createDoughnutChart() {
        return new DoughnutChart();
    }

    /**
     * Create an instance of {@link GetDoughnutChartResponse }
     * 
     */
    public GetDoughnutChartResponse createGetDoughnutChartResponse() {
        return new GetDoughnutChartResponse();
    }

    /**
     * Create an instance of {@link GetBarChartRequest }
     * 
     */
    public GetBarChartRequest createGetBarChartRequest() {
        return new GetBarChartRequest();
    }

    /**
     * Create an instance of {@link BarChart }
     * 
     */
    public BarChart createBarChart() {
        return new BarChart();
    }

    /**
     * Create an instance of {@link GetBarChartResponse }
     * 
     */
    public GetBarChartResponse createGetBarChartResponse() {
        return new GetBarChartResponse();
    }

    /**
     * Create an instance of {@link LineDataSet }
     * 
     */
    public LineDataSet createLineDataSet() {
        return new LineDataSet();
    }

    /**
     * Create an instance of {@link DoughnutDataSet }
     * 
     */
    public DoughnutDataSet createDoughnutDataSet() {
        return new DoughnutDataSet();
    }

    /**
     * Create an instance of {@link BarDataSet }
     * 
     */
    public BarDataSet createBarDataSet() {
        return new BarDataSet();
    }

}
